### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by livibetter** [esimov/gifter#1]
Linux, Go 1.7.3 and 1.7.4 (official binary), st terminal.

```
$ gifter examplers/nyan.gif

panic: runtime error: integer divide by zero

goroutine 7 [running]:
panic(0x5072c0, 0xc420010150)
        /home/livibetter/var/bin/go/src/runtime/panic.go:500 +0x1a1
main.(*GifImg).CellAvgRGB(0xc4200e6080, 0xc4200e6000, 0x0, 0x8000000000000000, 0x8000000000000000, 0x8000000000000000, 0x0, 0x0, 0x0)
        /tmp/tgo/src/github.com/esimov/gifter/image.go:48 +0x25c
main.draw.func2(0xc4200e6000, 0xc420106000, 0xc420106008, 0xc420106010, 0xc420106018, 0x7ff0000000000000, 0x7ff0000000000000, 0xc400000000, 0x0)
        /tmp/tgo/src/github.com/esimov/gifter/main.go:179 +0x193
created by main.draw
        /tmp/tgo/src/github.com/esimov/gifter/main.go:194 +0x3f8
```

Tried fullscreen terminal window, `TERM=xterm`, installed and ran from source repository, and a couple of images, all the same result. And I could only guess, somehow, `count++` wasn't never reached.

I don't know much of Go, so if anything more information you need from me, you might need to instruct me with explicit commands.

**Comment by esimov** [comment]
Issue fixed. The reason was Ubuntu does not have any information about the terminal width and height, only the columns and rows.
